### ISSUE TITLE
Journey cannot be started while using JavaAgent

### ISSUE THREAD

**Issue by zacsonskaria** [anotheria/moskito-javaagent#7]
Unable to start a Journey while using JavaAgent. As journey is triggered from the webpp filter, probably we should add some general filter to all webapps in tomcat configs.

**Comment by dvayanu** [comment]
This should be retested with latest version (2.8.5-SNAPSHOT) or built from trunk. I can imagine that the issue could be partially resolved. However, yes, triggering a journey via parameter won't happen unless some custom code says so.

**Comment by dvayanu** [comment]
This is now fixed with latest pull request. https://github.com/anotheria/moskito-javaagent/pull/18
